apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: myapp
data:
  NODE_ENV: 'production'
  PORT: '3001'
  CORS_ORIGINS: ''
  TRUST_PROXY: 'true'
  EXPO_PUBLIC_API_URL: 'http://app.local/api'
